# Generated by Django 2.1.7 on 2019-11-02 18:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(default='Name', max_length=200)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('age', models.IntegerField(default='999', max_length=3)),
                ('address', models.CharField(default='Address', max_length=480)),
                ('city', models.CharField(default='City', max_length=480)),
                ('state', models.CharField(default='XX', max_length=2)),
                ('zip_code', models.IntegerField(default=99999, max_length=5)),
                ('phone_number', models.IntegerField(default=9999999999, max_length=10)),
                ('illnesses', models.CharField(default='Illness', max_length=1000)),
                ('patient_description', models.CharField(default='Illness', max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_and_walk', models.CharField(default='Yes or No', max_length=1000)),
                ('nausea', models.CharField(default='Yes or No', max_length=1000)),
                ('pills_or_iv', models.CharField(default='Pills or IV', max_length=1000)),
                ('normal_breathing', models.CharField(default='Yes or No', max_length=1000)),
                ('normal_bp', models.CharField(default='Yes or No', max_length=1000)),
                ('peebility', models.CharField(default='Yes or No', max_length=1000)),
                ('bowel_movement_ok', models.CharField(default='Desc.', max_length=1000)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Patient')),
            ],
        ),
    ]
