# Generated by Django 2.1.7 on 2019-11-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.IntegerField(default=9999999999),
        ),
        migrations.AlterField(
            model_name='patient',
            name='zip_code',
            field=models.IntegerField(default=99999),
        ),
    ]
