# Generated by Django 2.1.7 on 2019-11-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20191102_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponses',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='bowel_movement_ok',
            field=models.CharField(default='Desc.', max_length=1000),
        ),
        migrations.AddField(
            model_name='patient',
            name='nausea',
            field=models.CharField(default='Yes or No', max_length=1000),
        ),
        migrations.AddField(
            model_name='patient',
            name='normal_bp',
            field=models.CharField(default='Yes or No', max_length=1000),
        ),
        migrations.AddField(
            model_name='patient',
            name='normal_breathing',
            field=models.CharField(default='Yes or No', max_length=1000),
        ),
        migrations.AddField(
            model_name='patient',
            name='peebility',
            field=models.CharField(default='Yes or No', max_length=1000),
        ),
        migrations.AddField(
            model_name='patient',
            name='pills_or_iv',
            field=models.CharField(default='Pills or IV', max_length=1000),
        ),
        migrations.AddField(
            model_name='patient',
            name='stand_and_walk',
            field=models.CharField(default='Yes or No', max_length=1000),
        ),
        migrations.DeleteModel(
            name='SurveyResponses',
        ),
    ]
